# Generated by Django 6.1 on 2026-08-30 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('structure', '0002_teacher_subject_grades_sectionsubject'),
        ('students', '0002_alter_student_options_alter_student_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.CharField(max_length=255, verbose_name='القيمة')),
            ],
            options={
                'verbose_name': 'إعداد',
                'verbose_name_plural': 'الإعدادات',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(help_text='نسخة من قيمة القاعدة وقت التطبيق — تبقى ثابتة حتى لو تغيّرت قيمة القاعدة لاحقًا', verbose_name='القيمة المطبّقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='سجّلتها')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='rules.rule', verbose_name='القاعدة المطبّقة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='students.student', verbose_name='الطالب')),
                ('subject', models.ForeignKey(blank=True, help_text='فاضي تلقائيًا لقواعد الإشراف العام', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='structure.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التصفير')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_resets', to=settings.AUTH_USER_MODEL, verbose_name='نفّذت التصفير')),
            ],
            options={
                'verbose_name': 'تصفير أسبوعي',
                'verbose_name_plural': 'سجل التصفير الأسبوعي',
                'ordering': ['-performed_at'],
            },
        ),
    ]
