# Generated by Django 6.1 on 2026-09-13 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        ('students', '0002_alter_student_options_alter_student_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='عدد النجوم المُحوَّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التحويل')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_purchases', to='students.student', verbose_name='الطالبة المستلِمة')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_pos_transactions', to=settings.AUTH_USER_MODEL, verbose_name='سجّلتها')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='students.student', verbose_name='الطالبة المُحوِّلة')),
            ],
            options={
                'verbose_name': 'عملية تحويل (تاجر التبيان)',
                'verbose_name_plural': 'عمليات تحويل تاجر التبيان',
                'ordering': ['-created_at'],
            },
        ),
    ]
