# Generated by Django 6.1 on 2026-09-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_postransaction'),
        ('students', '0002_alter_student_options_alter_student_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postransaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_purchases', to='students.student', verbose_name='الطرف المستلِم'),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='students.student', verbose_name='الطرف المُحوِّل'),
        ),
    ]
