# Generated by Django 6.1 on 2026-08-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0002_teacher_subject_grades_sectionsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=30, unique=True, verbose_name='رقم القيد')),
                ('full_name', models.CharField(max_length=150, verbose_name='اسم الطالبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='طالبة مسجّلة حاليًا')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='structure.section', verbose_name='الفصل')),
            ],
            options={
                'verbose_name': 'طالبة',
                'verbose_name_plural': 'الطالبات',
                'ordering': ['section__grade__number', 'section__name', 'full_name'],
            },
        ),
    ]
