# Generated by Django 6.1 on 2026-08-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['section__grade__number', 'section__name', 'full_name'], 'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='طالب مسجّل حاليًا'),
        ),
    ]
