# Generated by Django 6.1 on 2026-08-29 08:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('role', models.CharField(choices=[('super_admin', 'مسؤولة النظام (صلاحية كاملة)'), ('school_admin', 'مديرة المدرسة'), ('data_entry', 'موظفة إدخال البيانات')], max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='الحساب مفعّل')),
                ('is_staff', models.BooleanField(default=False, editable=False, verbose_name='يقدر يدخل لوحة /admin')),
                ('is_superuser', models.BooleanField(default=False, editable=False, verbose_name='صلاحية كاملة بلوحة /admin')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الحساب')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
