# Generated by Django 6.1 on 2026-08-29 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='رقم الصف')),
            ],
            options={
                'verbose_name': 'صف',
                'verbose_name_plural': 'الصفوف',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المادة')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('boys', 'بنين'), ('girls', 'بنات')], max_length=10, verbose_name='الجنس')),
                ('name', models.CharField(help_text='مثال: بنين، بنين 1، بنين 2، بنات', max_length=50, verbose_name='اسم الفصل')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='structure.grade', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'فصل',
                'verbose_name_plural': 'الفصول',
                'ordering': ['grade__number', 'gender', 'name'],
                'unique_together': {('grade', 'gender', 'name')},
            },
        ),
    ]
