# Generated by Django 6.1 on 2026-08-29 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='اسم المعلّمة')),
            ],
            options={
                'verbose_name': 'معلّمة',
                'verbose_name_plural': 'المعلّمات',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='grades',
            field=models.ManyToManyField(related_name='subjects', to='structure.grade', verbose_name='الصفوف اللي تُدرّس فيها'),
        ),
        migrations.CreateModel(
            name='SectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_subjects', to='structure.section', verbose_name='الفصل')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_subjects', to='structure.subject', verbose_name='المادة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_subjects', to='structure.teacher', verbose_name='المعلّمة')),
            ],
            options={
                'verbose_name': 'تدريس مادة لفصل',
                'verbose_name_plural': 'تدريس المواد للفصول',
                'ordering': ['section__grade__number', 'section__name', 'subject__name'],
                'unique_together': {('section', 'subject')},
            },
        ),
    ]
