# Generated by Django 6.1 on 2026-08-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0002_teacher_subject_grades_sectionsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: حل الواجب، تأخر عن الحصة', max_length=150, verbose_name='اسم القاعدة')),
                ('category', models.CharField(choices=[('subject', 'مادة'), ('general', 'إشراف عام')], max_length=10, verbose_name='التصنيف')),
                ('value', models.IntegerField(help_text='رقم موجب للإضافة، أو سالب للخصم', verbose_name='القيمة')),
                ('subject', models.ForeignKey(blank=True, help_text='اتركيه فاضي لو القاعدة تنطبق على كل المواد', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='structure.subject', verbose_name='مادة محددة (اختياري)')),
            ],
            options={
                'verbose_name': 'قاعدة تقييم',
                'verbose_name_plural': 'قواعد التقييم',
                'ordering': ['category', 'name'],
            },
        ),
    ]
