# Generated by Django 5.2.17 on 2026-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="is_range",
            field=models.BooleanField(
                default=False,
                help_text="مفعّلة: الموظفة تختار قيمة ضمن مدى وقت التطبيق (مثال: تكليف المعلّم 1 إلى 3)",
                verbose_name="قيمة متغيّرة (مدى)",
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="max_value",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="أعلى قيمة بالمدى"
            ),
        ),
        migrations.AddField(
            model_name="rule",
            name="min_value",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="أقل قيمة بالمدى"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="value",
            field=models.IntegerField(
                blank=True,
                help_text="رقم موجب للإضافة، أو سالب للخصم — تُترك فاضية لو القاعدة من نوع مدى",
                null=True,
                verbose_name="القيمة",
            ),
        ),
    ]