# Generated by Django 5.2.17 on 2026-09-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_rule_value_range"),
        ("structure", "0002_teacher_subject_grades_sectionsubject"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="grades",
            field=models.ManyToManyField(
                blank=True,
                help_text="لقواعد الاستبدال فقط — اتركيها فاضية لتنطبق على كل الصفوف",
                related_name="redemption_rules",
                to="structure.grade",
                verbose_name="صفوف محددة (اختياري)",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="category",
            field=models.CharField(
                choices=[
                    ("subject", "مادة"),
                    ("general", "إشراف عام"),
                    ("redemption", "استبدال"),
                ],
                max_length=10,
                verbose_name="التصنيف",
            ),
        ),
    ]